# Generated by Django 2.2.5 on 2019-09-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weight_lot_type', models.CharField(choices=[('lb.', 'lb.'), ('ton', 'ton'), ('kg.', 'kg.'), ('g', 'g')], default='kg.', max_length=10)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Other', 'Other')], default='Black', max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
