# Generated by Django 2.2.5 on 2019-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateField(),
        ),
    ]
