# Generated by Django 2.2.5 on 2019-09-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shipment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Height'),
        ),
    ]
