# Generated by Django 2.2.5 on 2019-09-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190927_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='shipment',
            name='author',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
